name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t my-node-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ farhanuzzaman }}
          password: ${{ furtHuck@20 }}

      - name: Push Docker image
        run: |
          docker tag my-node-app:latest ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
